export const towerDefinitionsSeed = [
  // ========== STARTER TOWERS (Level 1) ==========
  {
    towerType: 'basic',
    baseName: 'Sentinel Crossbow',
    category: 'physical',
    unlockLevel: 1,
    baseCost: 100,
    baseDamage: 10,
    baseRange: 120,
    baseFireRate: 1.0,
    description: 'Ancient automated defense system. Reliable, precise, and proven in countless battles.',
    lore: 'The Sentinel Crossbow was the first automated defense system created during the First Void War. Its simple yet effective design has protected countless outposts.',
    icon: '🏹',
    rarity: 'common',
  },

  // ========== EARLY GAME (Levels 2-10) ==========
  {
    towerType: 'slow',
    baseName: 'Gravity Well',
    category: 'support',
    unlockLevel: 2,
    baseCost: 150,
    baseDamage: 2,
    baseRange: 100,
    baseFireRate: 0.5,
    description: 'Manipulates spacetime to slow enemy movement. Essential for controlling enemy advances.',
    lore: 'Discovered by accident when a power core overloaded. The resulting spacetime distortion proved invaluable for defense.',
    icon: '🌀',
    rarity: 'common',
  },
  {
    towerType: 'cannon',
    baseName: 'Thunder Howitzer',
    category: 'physical',
    unlockLevel: 4,
    baseCost: 180,
    baseDamage: 25,
    baseRange: 140,
    baseFireRate: 0.4,
    description: 'Heavy artillery with devastating area-of-effect damage. Slow but powerful.',
    lore: 'Named after the thunderous boom it creates, this howitzer can shatter enemy formations with a single shell.',
    icon: '💥',
    rarity: 'common',
  },
  {
    towerType: 'ice',
    baseName: 'Cryo Stasis Matrix',
    category: 'elemental',
    unlockLevel: 6,
    baseCost: 160,
    baseDamage: 5,
    baseRange: 110,
    baseFireRate: 0.8,
    description: 'Freezes enemies solid with sub-zero energy beams. Can completely immobilize targets.',
    lore: 'Developed in the frozen wastes of Sector 7, this technology harnesses absolute zero temperatures.',
    icon: '❄️',
    rarity: 'common',
  },
  {
    towerType: 'sniper',
    baseName: 'Void Piercer',
    category: 'physical',
    unlockLevel: 8,
    baseCost: 200,
    baseDamage: 35,
    baseRange: 200,
    baseFireRate: 0.3,
    description: 'Ultra-long-range precision weapon. One shot, one kill philosophy.',
    lore: 'Fitted with Void-tech targeting systems, this sniper can pierce through reality itself to strike its target.',
    icon: '🎯',
    rarity: 'rare',
  },
  {
    towerType: 'generator',
    baseName: 'Resource Harvester',
    category: 'economic',
    unlockLevel: 10,
    baseCost: 250,
    baseDamage: 0,
    baseRange: 0,
    baseFireRate: 0,
    description: 'Generates bonus resources over time. Essential for economic strategies.',
    lore: 'Extracts latent energy from the battlefield itself, converting chaos into usable resources.',
    icon: '💰',
    rarity: 'rare',
  },

  // ========== MID GAME (Levels 11-25) ==========
  {
    towerType: 'fire',
    baseName: 'Inferno Conduit',
    category: 'elemental',
    unlockLevel: 12,
    baseCost: 220,
    baseDamage: 15,
    baseRange: 130,
    baseFireRate: 0.7,
    description: 'Channels pure flame that burns enemies over time. Spreads fire to nearby foes.',
    lore: 'Contains a fragment of a dying star. The heat it generates is said to rival the core of planets.',
    icon: '🔥',
    rarity: 'rare',
  },
  {
    towerType: 'poison',
    baseName: 'Plague Spewer',
    category: 'elemental',
    unlockLevel: 14,
    baseCost: 180,
    baseDamage: 8,
    baseRange: 120,
    baseFireRate: 0.6,
    description: 'Bio-engineered toxin spreader. Poisons multiple enemies with each attack.',
    lore: 'Created by rogue scientists, this weapon was deemed too dangerous for conventional warfare.',
    icon: '☠️',
    rarity: 'rare',
  },
  {
    towerType: 'amplifier',
    baseName: 'Damage Amplifier',
    category: 'support',
    unlockLevel: 16,
    baseCost: 300,
    baseDamage: 0,
    baseRange: 150,
    baseFireRate: 0,
    description: 'Boosts damage of nearby towers by 25%. Synergy is key.',
    lore: 'Uses resonance fields to amplify the destructive potential of all nearby weapons.',
    icon: '📡',
    rarity: 'epic',
  },
  {
    towerType: 'lightning',
    baseName: 'Storm Caller',
    category: 'elemental',
    unlockLevel: 18,
    baseCost: 240,
    baseDamage: 20,
    baseRange: 140,
    baseFireRate: 0.5,
    description: 'Summons chain lightning that jumps between enemies. High voltage devastation.',
    lore: 'Forged during an eternal storm, this tower commands the very skies themselves.',
    icon: '⚡',
    rarity: 'epic',
  },
  {
    towerType: 'laser',
    baseName: 'Photon Beam Array',
    category: 'energy',
    unlockLevel: 20,
    baseCost: 280,
    baseDamage: 18,
    baseRange: 160,
    baseFireRate: 1.2,
    description: 'Rapid-fire laser beams that never miss. Sustained damage over time.',
    lore: 'Quantum-locked photons ensure 100% hit accuracy. Physics itself bends to this weapon.',
    icon: '🔴',
    rarity: 'epic',
  },
  {
    towerType: 'arcane',
    baseName: 'Aether Spire',
    category: 'magic',
    unlockLevel: 22,
    baseCost: 320,
    baseDamage: 30,
    baseRange: 150,
    baseFireRate: 0.4,
    description: 'Mystical energy bolts that ignore armor. Pure magical destruction.',
    lore: 'Built from crystallized magic itself, this spire taps into dimensions beyond comprehension.',
    icon: '✨',
    rarity: 'epic',
  },

  // ========== LATE GAME (Levels 26-40) ==========
  {
    towerType: 'tesla',
    baseName: 'Tesla Resonator',
    category: 'energy',
    unlockLevel: 25,
    baseCost: 350,
    baseDamage: 25,
    baseRange: 180,
    baseFireRate: 0.6,
    description: 'Continuous electric arc that chains through multiple enemies. Constant pressure.',
    lore: 'Based on forbidden research, this device creates perpetual energy loops that devastate everything in range.',
    icon: '⚡',
    rarity: 'epic',
  },
  {
    towerType: 'rocket',
    baseName: 'MIRV Launcher',
    category: 'physical',
    unlockLevel: 28,
    baseCost: 400,
    baseDamage: 40,
    baseRange: 170,
    baseFireRate: 0.3,
    description: 'Multiple Independent Re-entry Vehicles. One rocket splits into many.',
    lore: 'Military-grade ordinance repurposed for tower defense. Each warhead is a miniature apocalypse.',
    icon: '🚀',
    rarity: 'legendary',
  },
  {
    towerType: 'black_hole',
    baseName: 'Singularity Core',
    category: 'exotic',
    unlockLevel: 30,
    baseCost: 500,
    baseDamage: 50,
    baseRange: 130,
    baseFireRate: 0.2,
    description: 'Creates miniature black holes that pull in and crush enemies. Ultimate destruction.',
    lore: 'Containment failure means instant death. Only the most skilled commanders dare use this weapon.',
    icon: '🕳️',
    rarity: 'legendary',
  },
  {
    towerType: 'time_warp',
    baseName: 'Temporal Anomaly',
    category: 'exotic',
    unlockLevel: 35,
    baseCost: 450,
    baseDamage: 10,
    baseRange: 140,
    baseFireRate: 1.0,
    description: 'Rewinds enemy progress and causes temporal damage. Manipulates the flow of time itself.',
    lore: 'Stolen from a future that may never exist. This technology should not be possible.',
    icon: '⏰',
    rarity: 'legendary',
  },
  {
    towerType: 'plasma',
    baseName: 'Fusion Devastator',
    category: 'energy',
    unlockLevel: 40,
    baseCost: 600,
    baseDamage: 60,
    baseRange: 150,
    baseFireRate: 0.4,
    description: 'Superheated plasma that melts through anything. The ultimate offensive weapon.',
    lore: 'Contains a miniaturized star. The energy output is almost incomprehensible.',
    icon: '☄️',
    rarity: 'legendary',
  },

  // ========== PRESTIGE (Levels 41-50) ==========
  {
    towerType: 'void',
    baseName: 'Void Annihilator',
    category: 'exotic',
    unlockLevel: 45,
    baseCost: 800,
    baseDamage: 100,
    baseRange: 200,
    baseFireRate: 0.2,
    description: 'Tears holes in reality itself. Enemies simply cease to exist.',
    lore: 'The pinnacle of Void technology. Reality itself bends and breaks at its command.',
    icon: '🌌',
    rarity: 'legendary',
  },
  {
    towerType: 'omega',
    baseName: 'Omega Protocol',
    category: 'exotic',
    unlockLevel: 50,
    baseCost: 1000,
    baseDamage: 150,
    baseRange: 250,
    baseFireRate: 0.3,
    description: 'The ultimate defense system. All other towers are obsolete.',
    lore: 'The final weapon. When this is deployed, victory or oblivion are the only outcomes.',
    icon: '💫',
    rarity: 'legendary',
  },
];
