export const towerDefinitionsSeed = [
  // ========== STARTER TOWERS (Level 1) ==========
  {
    tower_type: 'basic',
    base_name: 'Sentinel Crossbow',
    category: 'physical',
    unlock_level: 1,
    base_cost: 100,
    base_damage: 10,
    base_range: 120,
    base_fire_rate: 1.0,
    description: 'Ancient automated defense system. Reliable, precise, and proven in countless battles.',
    lore: 'The Sentinel Crossbow was the first automated defense system created during the First Void War. Its simple yet effective design has protected countless outposts.',
    icon: '🏹',
    rarity: 'common',
  },

  // ========== EARLY GAME (Levels 2-10) ==========
  {
    tower_type: 'slow',
    base_name: 'Gravity Well',
    category: 'support',
    unlock_level: 2,
    base_cost: 150,
    base_damage: 2,
    base_range: 100,
    base_fire_rate: 0.5,
    description: 'Manipulates spacetime to slow enemy movement. Essential for controlling enemy advances.',
    lore: 'Discovered by accident when a power core overloaded. The resulting spacetime distortion proved invaluable for defense.',
    icon: '🌀',
    rarity: 'common',
  },
  {
    tower_type: 'cannon',
    base_name: 'Thunder Howitzer',
    category: 'physical',
    unlock_level: 4,
    base_cost: 180,
    base_damage: 25,
    base_range: 140,
    base_fire_rate: 0.4,
    description: 'Heavy artillery with devastating area-of-effect damage. Slow but powerful.',
    lore: 'Named after the thunderous boom it creates, this howitzer can shatter enemy formations with a single shell.',
    icon: '💥',
    rarity: 'common',
  },
  {
    tower_type: 'ice',
    base_name: 'Cryo Stasis Matrix',
    category: 'elemental',
    unlock_level: 6,
    base_cost: 160,
    base_damage: 5,
    base_range: 110,
    base_fire_rate: 0.8,
    description: 'Freezes enemies solid with sub-zero energy beams. Can completely immobilize targets.',
    lore: 'Developed in the frozen wastes of Sector 7, this technology harnesses absolute zero temperatures.',
    icon: '❄️',
    rarity: 'common',
  },
  {
    tower_type: 'sniper',
    base_name: 'Void Piercer',
    category: 'physical',
    unlock_level: 8,
    base_cost: 200,
    base_damage: 35,
    base_range: 200,
    base_fire_rate: 0.3,
    description: 'Ultra-long-range precision weapon. One shot, one kill philosophy.',
    lore: 'Fitted with Void-tech targeting systems, this sniper can pierce through reality itself to strike its target.',
    icon: '🎯',
    rarity: 'rare',
  },
  {
    tower_type: 'generator',
    base_name: 'Resource Harvester',
    category: 'economic',
    unlock_level: 10,
    base_cost: 250,
    base_damage: 0,
    base_range: 0,
    base_fire_rate: 0,
    description: 'Generates bonus resources over time. Essential for economic strategies.',
    lore: 'Extracts latent energy from the battlefield itself, converting chaos into usable resources.',
    icon: '💰',
    rarity: 'rare',
  },

  // ========== MID GAME (Levels 11-25) ==========
  {
    tower_type: 'fire',
    base_name: 'Inferno Conduit',
    category: 'elemental',
    unlock_level: 12,
    base_cost: 220,
    base_damage: 15,
    base_range: 130,
    base_fire_rate: 0.7,
    description: 'Channels pure flame that burns enemies over time. Spreads fire to nearby foes.',
    lore: 'Contains a fragment of a dying star. The heat it generates is said to rival the core of planets.',
    icon: '🔥',
    rarity: 'rare',
  },
  {
    tower_type: 'poison',
    base_name: 'Plague Spewer',
    category: 'elemental',
    unlock_level: 14,
    base_cost: 180,
    base_damage: 8,
    base_range: 120,
    base_fire_rate: 0.6,
    description: 'Bio-engineered toxin spreader. Poisons multiple enemies with each attack.',
    lore: 'Created by rogue scientists, this weapon was deemed too dangerous for conventional warfare.',
    icon: '☠️',
    rarity: 'rare',
  },
  {
    tower_type: 'amplifier',
    base_name: 'Damage Amplifier',
    category: 'support',
    unlock_level: 16,
    base_cost: 300,
    base_damage: 0,
    base_range: 150,
    base_fire_rate: 0,
    description: 'Boosts damage of nearby towers by 25%. Synergy is key.',
    lore: 'Uses resonance fields to amplify the destructive potential of all nearby weapons.',
    icon: '📡',
    rarity: 'epic',
  },
  {
    tower_type: 'lightning',
    base_name: 'Storm Caller',
    category: 'elemental',
    unlock_level: 18,
    base_cost: 240,
    base_damage: 20,
    base_range: 140,
    base_fire_rate: 0.5,
    description: 'Summons chain lightning that jumps between enemies. High voltage devastation.',
    lore: 'Forged during an eternal storm, this tower commands the very skies themselves.',
    icon: '⚡',
    rarity: 'epic',
  },
  {
    tower_type: 'laser',
    base_name: 'Photon Beam Array',
    category: 'energy',
    unlock_level: 20,
    base_cost: 280,
    base_damage: 18,
    base_range: 160,
    base_fire_rate: 1.2,
    description: 'Rapid-fire laser beams that never miss. Sustained damage over time.',
    lore: 'Quantum-locked photons ensure 100% hit accuracy. Physics itself bends to this weapon.',
    icon: '🔴',
    rarity: 'epic',
  },
  {
    tower_type: 'arcane',
    base_name: 'Aether Spire',
    category: 'magic',
    unlock_level: 22,
    base_cost: 320,
    base_damage: 30,
    base_range: 150,
    base_fire_rate: 0.4,
    description: 'Mystical energy bolts that ignore armor. Pure magical destruction.',
    lore: 'Built from crystallized magic itself, this spire taps into dimensions beyond comprehension.',
    icon: '✨',
    rarity: 'epic',
  },

  // ========== LATE GAME (Levels 26-40) ==========
  {
    tower_type: 'tesla',
    base_name: 'Tesla Resonator',
    category: 'energy',
    unlock_level: 25,
    base_cost: 350,
    base_damage: 25,
    base_range: 180,
    base_fire_rate: 0.6,
    description: 'Continuous electric arc that chains through multiple enemies. Constant pressure.',
    lore: 'Based on forbidden research, this device creates perpetual energy loops that devastate everything in range.',
    icon: '⚡',
    rarity: 'epic',
  },
  {
    tower_type: 'rocket',
    base_name: 'MIRV Launcher',
    category: 'physical',
    unlock_level: 28,
    base_cost: 400,
    base_damage: 40,
    base_range: 170,
    base_fire_rate: 0.3,
    description: 'Multiple Independent Re-entry Vehicles. One rocket splits into many.',
    lore: 'Military-grade ordinance repurposed for tower defense. Each warhead is a miniature apocalypse.',
    icon: '🚀',
    rarity: 'legendary',
  },
  {
    tower_type: 'black_hole',
    base_name: 'Singularity Core',
    category: 'exotic',
    unlock_level: 30,
    base_cost: 500,
    base_damage: 50,
    base_range: 130,
    base_fire_rate: 0.2,
    description: 'Creates miniature black holes that pull in and crush enemies. Ultimate destruction.',
    lore: 'Containment failure means instant death. Only the most skilled commanders dare use this weapon.',
    icon: '🕳️',
    rarity: 'legendary',
  },
  {
    tower_type: 'time_warp',
    base_name: 'Temporal Anomaly',
    category: 'exotic',
    unlock_level: 35,
    base_cost: 450,
    base_damage: 10,
    base_range: 140,
    base_fire_rate: 1.0,
    description: 'Rewinds enemy progress and causes temporal damage. Manipulates the flow of time itself.',
    lore: 'Stolen from a future that may never exist. This technology should not be possible.',
    icon: '⏰',
    rarity: 'legendary',
  },
  {
    tower_type: 'plasma',
    base_name: 'Fusion Devastator',
    category: 'energy',
    unlock_level: 40,
    base_cost: 600,
    base_damage: 60,
    base_range: 150,
    base_fire_rate: 0.4,
    description: 'Superheated plasma that melts through anything. The ultimate offensive weapon.',
    lore: 'Contains a miniaturized star. The energy output is almost incomprehensible.',
    icon: '☄️',
    rarity: 'legendary',
  },

  // ========== PRESTIGE (Levels 41-50) ==========
  {
    tower_type: 'void',
    base_name: 'Void Annihilator',
    category: 'exotic',
    unlock_level: 45,
    base_cost: 800,
    base_damage: 100,
    base_range: 200,
    base_fire_rate: 0.2,
    description: 'Tears holes in reality itself. Enemies simply cease to exist.',
    lore: 'The pinnacle of Void technology. Reality itself bends and breaks at its command.',
    icon: '🌌',
    rarity: 'legendary',
  },
  {
    tower_type: 'omega',
    base_name: 'Omega Protocol',
    category: 'exotic',
    unlock_level: 50,
    base_cost: 1000,
    base_damage: 150,
    base_range: 250,
    base_fire_rate: 0.3,
    description: 'The ultimate defense system. All other towers are obsolete.',
    lore: 'The final weapon. When this is deployed, victory or oblivion are the only outcomes.',
    icon: '💫',
    rarity: 'legendary',
  },
];
